---
- name: install basic packages
  apt: name={{ item }}
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev
    - libmysqlclient-dev
    - ntp
    - zip
    - tmux
    - xclip
    - imagemagick
    - nfs-common
  sudo: true
  tags: basic-packages
