---
- name: restart sshd
  service: name=ssh state=restarted
  sudo: true

- name: restart ntp
  service: name=ntpd state=restarted
  sudo: true

- name: restart docker
  service: name=docker state=restarted
  sudo: true
